## 常用的NumPy数组对象创建方式

+ np.array()
接受list对象

+ np.ones(n)
+ np.zeros(n)
+ np.arange(n) <-> np.array([0,1,2,...,n-1])

## 与标量运算

+ 数组与标量之间的运算将会应用到每个元素上。eg. 1/arr; arr \*\* 0.5
+ 同维度的数组之间进行运算时作用域相同位置的元素之间运算。eg. arr * arr; arr - arr

## 索引与切片 

### 普通切片
如一维的数组arr[1:4],这样的选区对象可以整体赋值。  
把切片对象赋值给其他变量，仅仅是相当于引用，并没有对源数组对象进行复制。使用arr.copy()方法可以手动复制成新的内存对象。    
二维数组选区形式：arr[a:b, c:d]
### 布尔型索引
bool_array = ...  
arr[bool_array]   
如果是arr是多维数组arr[bool_array]表示根据bool_array数组选区哪些行，当然也可以在[]中添加对其他维的选取。  
注意使用布尔型索引选取的数组中的数据，总是会产生新的内存对象。  
数组转置arr.T,注不产生新副本。  


## 通用函数

作用于元素级的numpy通用函数 eg. np.abs(arr)
### 一元ufunc
abs(), fabs(), sqrt(), square()  
exp(), log(), log10(), log2(), log1p(x) <-> log(1+x)  
sign(), ceil(), floor(), rint(x) <-> 四舍五入  
modf():整数和小数部分分离成两个独立的数组返回  
isnan(), isfinite(), isinf()   
cos(), sin(), tan(), arccos(), arcsin(), arctan()  
logical_not(arr) <->  -arr  
### 二元ufunc
add(arr1,arr2), subtract(), multiply(), divide(), floor_divide(), power()  
maxinum(), fmax()  
mininum(), fmin()  
mod()  
逻辑运算 greater(), greater_equal(), equal(), logical_and(), logical_or(), logical_xor()  

## np.where()条件表达式

使用numpy自带的方法比if,for要效率要高些。

In [5]:
import numpy as np
arr = np.random.randn(4, 4)
arr
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.        , -0.33287134,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.88559764],
       [ 2.        ,  2.        , -1.13396698, -0.32575847],
       [-0.91340307,  2.        ,  2.        , -0.63273916]])

## 基本统计方法

sum(axis=1)  计算各列的和  
mean(axis=1) 计算各列的算术平均数  
std(), var() 标准差和方差  
min(), max()   
argmax(), argmin() 返回最大值和最小的索引位置  
cumsum()    所有元素的累计和  
cumprod()    所有元素的累计积  
any()  是否存在非零的元素  
all()  是否不存在非零的元素  


## 排序

argsort函数返回的是数组值从小到大的索引值

In [6]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [17]:
x = np.array([[3,1,2],[0,4,1]])
np.sort(x, axis=0)

array([[0, 1, 1],
       [3, 4, 2]])

arr[:,0].sort()  按第一列排序

## 集合运算
unique(x)      计算x中的唯一元素  
intersect1d(x,y)  计算x和y的公共元素，并返回有序结果  
union1d(x,y)    计算x和y的病机，并返回有序结果   
in1d(x,y)      得到一个表示“x的元素是否包含于y”的布尔型数组   
setdiff1d(x,y)   集合的差，即元素在x中且不在y中   
setxor1d(x,y)   集合的对称差，即存在于一个数组中但不同时存在于两个数组中的元素   

## 文本文件输入输出
arr = np.loadtxt(fname, dtype=float, delimiter='\t', skiprows=0)  
np.savetxt(fname, arr, fmt='%.18e', delimiter=',', newline='\n', header='')

## numpy线性代数方法
diag  以一维数组的形式返回方阵的对角线元素，或将一维数组转换为方阵（非对角线元素为0）  
dot   矩阵乘法  
trace  计算对角线元素的和  
det   计算矩阵行列式  
eig   计算方阵的本征值和本征向量  
inv   计算方阵的逆  
pinv  计算矩阵的Moore-Penrose伪逆  
qr   计算QR分解  
svd   计算奇异值分解  
slove  解线性方程组Ax = b, 其中A为一个方阵  
lstsq  计算Ax = b的最小二乘解  

## numpy.random函数
seed   确定随机数生成器的种子  
permulation   返回一个序列的随机排列或返回一个随机排列的范围   
shuffle    对一个序列就地随机排列   
rand    产生均匀分布的样本值    
randint   从给定的上下限范围内随机选取整数    
randn   产生正态分布（平均值为0，标准差为1）的样本值   
binomial   产生二项分布的样本值    
normal    产生正态（高斯）分布的样本值   
beta   产生Beta分布的样本值    
chisquare   产生卡方分布的样本值   
gamma   产生Gamma分布的样本值    
uniform   产生在[0,1)中均匀分布的样本值   

## 高级数组操作
arr.reshape(n,m) #多维数组重塑维度  
arr.ravel() #扁平化，多维变一维  
np.concatenate([arr1, arr2], axis=0) 数组合并，axis=1按列合并    

In [18]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [19]:
np.vstack((arr1,arr2)) 
np.hstack((arr1,arr2)) 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [24]:
from numpy.random import randn
arr = randn(5, 2)
arr
first, second, third = np.split(arr, [1, 3], axis=0)
first
second
third

array([[-0.1831409 , -0.4704608 ],
       [ 0.71055879, -1.20932075]])

### 堆叠辅助类：r_和c_

In [26]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = randn(3, 2)
np.r_[arr1, arr2]
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-0.64537248, -1.00749446,  3.        ],
       [-0.02896785, -1.07243211,  4.        ],
       [ 0.28989067,  0.71906017,  5.        ]])

## 元素重复操作：tile和repeat

In [27]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [28]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [32]:
arr = randn(2, 2)
arr
arr.repeat(2, axis=0)

array([[ 1.16098708, -0.15680169],
       [ 1.16098708, -0.15680169],
       [ 0.12064578, -0.35940716],
       [ 0.12064578, -0.35940716]])

In [33]:
arr.repeat([2, 3], axis=0)
arr.repeat([2, 3], axis=1)

array([[ 1.16098708,  1.16098708, -0.15680169, -0.15680169, -0.15680169],
       [ 0.12064578,  0.12064578, -0.35940716, -0.35940716, -0.35940716]])

In [34]:
arr
np.tile(arr, 2)

array([[ 1.16098708, -0.15680169,  1.16098708, -0.15680169],
       [ 0.12064578, -0.35940716,  0.12064578, -0.35940716]])

In [35]:
arr
np.tile(arr, (2, 1))
np.tile(arr, (3, 2))

array([[ 1.16098708, -0.15680169,  1.16098708, -0.15680169],
       [ 0.12064578, -0.35940716,  0.12064578, -0.35940716],
       [ 1.16098708, -0.15680169,  1.16098708, -0.15680169],
       [ 0.12064578, -0.35940716,  0.12064578, -0.35940716],
       [ 1.16098708, -0.15680169,  1.16098708, -0.15680169],
       [ 0.12064578, -0.35940716,  0.12064578, -0.35940716]])

## take和put函数

# 参考资料

+ [《Python For Data Analysis》](http://book.douban.com/subject/10760444/)
+ [NumPy User Guide](http://docs.scipy.org/doc/numpy-dev/user/)
+ [numpy的random模块](http://www.cnblogs.com/hhh5460/p/4324967.html)